import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { AppProvider } from "@/providers/app-provider";
import { SideNav } from "@/components/widgets/side-nav";
import { SideNavWrapper } from "@/components/widgets/side-nav/side-nav-wrapper";
import { Header } from "@/components/widgets/header";
import { Button } from "@/components/common/ui/button";
import { RiPlayLine } from "react-icons/ri";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="dark" suppressHydrationWarning lang="en">
      <body className={`${inter.className}`}>
        <AppProvider>
          <div className="flex min-h-screen max-h-screen">
            <SideNav />
            <SideNavWrapper>
              <div className="flex flex-col h-full max-h-full overflow-y-auto overflow-x-hidden w-full mb-auto">
                <Header />
                <div className="mb-auto">{children}</div>
                <footer className="flex items-center gap-3 bg-background/80 backdrop-blur-md p-3 border-t sticky bottom-0 ">
                  <div className="w-12 h-12 bg-white flex items-center justify-center rounded-md">
                    <div className="w-3 h-3 bg-black rounded-full"></div>
                    <div className="w-3 h-3 bg-black rounded-full"></div>
                  </div>
                  <div className="flex flex-col flex-1">
                    <h1 className="font-mediumt text-lg">Selfish Love</h1>
                    <span className="text-xs">Selena Gomez</span>
                  </div>
                  <Button variant="ghost" className="aspect-square p-2 text-lg">
                    <RiPlayLine />
                  </Button>
                </footer>
              </div>
            </SideNavWrapper>
          </div>
        </AppProvider>
      </body>
    </html>
  );
}
